# Generated by Django 5.0.3 on 2024-03-27 11:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_alter_habit_pleasant_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='frequency',
            field=models.CharField(choices=[('Daily', 'D'), ('Monday', 'M'), ('Tuesday', 'T'), ('Wednesday', 'WE'), ('Thursday', 'TH'), ('Friday', 'FR'), ('Saturday', 'SAT'), ('Sunday', 'SUN')], default='Daily', verbose_name='Частота'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='time',
            field=models.TimeField(default=datetime.time(11, 11, 32, 285072), verbose_name='Время старта привычки'),
        ),
    ]
