# Generated by Django 5.0.3 on 2024-04-03 09:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0005_alter_habit_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='time',
            field=models.TimeField(default=datetime.time(9, 56, 57, 615902), verbose_name='Время старта привычки'),
        ),
    ]
